stages:
  featurize:
    cmd: python src/featurization.py data/
    deps:
    - data/
    - src/featurization.py
    params:
    - featurize.img_width
    - featurize.img_height
    - featurize.nb_validation_samples
    - featurize.batch_size
    outs:
    - features/
  train:
    cmd: python train_tensorflow.py features/
    deps:
    - features/
    - train_tensorflow.py
    params:
    - train.epochs
    - featurize.nb_validation_samples
    - featurize.batch_size
    outs:
    - model.h5
    metrics:
    - metrics.csv:
        cache: false
