stages:
  train:
    cmd: python train_tensorflow.py
    deps:
    - data
    - train_tensorflow.py
    outs:
    - bottleneck_features_train.npy
    - bottleneck_features_validation.npy
    - model.h5
    metrics:
    - metrics.csv:
        cache: false
